local lights = {
    -- Left side (1 --> 6)
    {
        id = 1,
        type = "column",
        side = "left",
        level = "bottom",
        enabled = false,
    },
    {
        id = 2,
        type = "diagonnal",
        side = "left",
        level = "bottom",
        enabled = false,
    },
    {
        id = 3,
        type = "column",
        side = "left",
        level = "bottom",
        enabled = false,
    },
    {
        id = 4,
        type = "column",
        side = "left",
        level = "bottom",
        enabled = false,
    },
    {
        id = 5,
        type = "diagonnal",
        side = "left",
        level = "top",
        enabled = false,
    },
    {
        id = 6,
        type = "column",
        side = "left",
        level = "top",
        enabled = false,
    },
    -- Back side (7 --> 15)
    {
        id = 7,
        type = "column",
        side = "back",
        level = "bottom",
        enabled = false,
    },
    {
        id = 8,
        type = "diagonnal",
        side = "back",
        level = "bottom",
        enabled = false,
    },
    {
        id = 9,
        type = "column",
        side = "back",
        level = "bottom",
        enabled = false,
    },
    {
        id = 10,
        type = "diagonnal",
        side = "back",
        level = "bottom",
        enabled = false,
    },
    {
        id = 11,
        type = "column",
        side = "back",
        level = "top",
        enabled = false,
    },
    {
        id = 12,
        type = "diagonnal",
        side = "back",
        level = "top",
        enabled = false,
    },
    {
        id = 13,
        type = "column",
        side = "back",
        level = "top",
        enabled = false,
    },
    {
        id = 14,
        type = "diagonnal",
        side = "back",
        level = "top",
        enabled = false,
    },
    {
        id = 15,
        type = "column",
        side = "back",
        level = "top",
        enabled = false,
    },
    -- Right side (16 --> 24)
    {
        id = 16,
        type = "column",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 17,
        type = "diagonnal",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 18,
        type = "column",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 19,
        type = "diagonnal",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 20,
        type = "column",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 21,
        type = "diagonnal",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 22,
        type = "column",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 23,
        type = "column",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    {
        id = 24,
        type = "diagonnal",
        side = "right",
        level = "bottom",
        enabled = false,
    },
    -- Top (25 --> 30)
    {
        id = 25,
        type = "diagonnal",
        side = "front",
        level = "top",
        enabled = false,
    },
    {
        id = 26,
        type = "diagonnal",
        side = "front",
        side = "top",
        enabled = false,
    },
    {
        id = 27,
        type = "diagonnal",
        side = "front",
        level = "top",
        enabled = false,
    },
    {
        id = 28,
        type = "diagonnal",
        side = "front",
        level = "top",
        enabled = false,
    },
    {
        id = 29,
        type = "diagonnal",
        side = "front",
        level = "top",
        enabled = false,
    },
    {
        id = 30,
        type = "diagonnal",
        side = "front",
        level = "top",
        enabled = false,
    },
    -- DJ (31 --> 32)
    {
        id = 31,
        type = "column",
        side = "front",
        level = "mid",
        enabled = false,
    },
    {
        id = 32,
        type = "column",
        side = "front",
        level = "mid",
        enabled = false,
    },
}

return lights